---
- hosts: all
  gather_facts: yes


  vars:
    home: /opt/atviriduomenys.lt
    path: "{{ home }}/app"
    env: production

  vars_files:
    - vars/{{ env }}.yml


  tasks:

  - name: update locale
    locale_gen: name={{ item }} state=present
    with_items:
    - en_US.UTF-8
    - lt_LT.UTF-8

  - name: apt repositories
    apt_repository: "repo='deb-src http://ubuntu-archive.mirror.serveriai.lt/ {{ ansible_distribution_release }} main restricted universe' state=present"

  - name: apt packages
    apt: pkg={{ item }} state=latest
    with_items:
    - build-essential
    - postgresql
    - python-psycopg2
    - python-dev
    - python-pip
    - python-virtualenv
    - apache2
    - libapache2-mod-wsgi-py3
    - git

  - name: create atviriduomenys user
    user: name=atviriduomenys system=yes group=www-data home={{ home }}

  - name: postgresql database
    postgresql_db: >
      name=atviriduomenys
      encoding='UTF-8'
      lc_collate='C.UTF-8'
      lc_ctype='C.UTF-8'
      template='template0'
    become_user: postgres

  - name: postgresql user
    postgresql_user: db=atviriduomenys name=atviriduomenys priv=ALL
    become_user: postgres

  - name: clone repository
    git: repo=https://github.com/ivpk/metadata dest={{ path }} force=yes
    notify: reload apache
    become_user: atviriduomenys

  - name: install python requirements to virtualenv
    pip:
      chdir: "{{ path }}"
      virtualenv: env
      virtualenv_python: python3
      requirements: requirements.txt
      state: present
    become_user: atviriduomenys
    tags: local

  - name: install project into virtualenv
    pip:
      chdir: "{{ path }}"
      virtualenv: env
      virtualenv_python: python3
      name: "."
      editable: true
      state: present
    become_user: atviriduomenys
    tags: local

  - name: migrate database
    command: env/bin/manage.py migrate --noinput chdir={{ path }}
    become_user: atviriduomenys

  - name: collectstatic
    command: env/bin/manage.py collectstatic --noinput chdir={{ path }}
    become_user: atviriduomenys

  - name: set up apache virtual host
    template: src=templates/apache.conf dest=/etc/apache2/sites-enabled/atviriduomenys.lt.conf
    notify: reload apache

  - name: create log dir
    file: path=/var/log/apache2/atviriduomenys.lt state=directory

  - name: create data dir
    file: path={{ path }}/var/www/data state=directory
    become_user: atviriduomenys

  - name: start apache
    service: name=apache2 state=started


  handlers:

  - name: reload apache
    service: name=apache2 state=reloaded
