---
- hosts: all
  gather_facts: yes

  vars:
    home: /opt/atviriduomenys.lt

  environment:
    PYENV_ROOT: /opt/atviriduomenys.lt/pyenv

  tasks:

    - name: update locale
      locale_gen: name={{ item }} state=present
      with_items:
      - en_US.UTF-8
      - lt_LT.UTF-8

    - name: apt repositories
      apt_repository: "repo='deb-src http://ubuntu-archive.mirror.serveriai.lt/ {{ ansible_distribution_release }} main restricted universe' state=present"

    - name: apt packages
      apt:
        pkg:
          - build-essential
          - postgresql
          - python-psycopg2
          - python-dev
          - python-pip
          - python-virtualenv
          - apache2
          - git
        state: latest

    - name: create atviriduomenys user
      user: name=atviriduomenys system=yes group=www-data home={{ home }}

    - name: postgresql database
      postgresql_db: name=atviriduomenys encoding='UTF-8' lc_collate='C.UTF-8' lc_ctype='C.UTF-8' template='template0'
      become_user: postgres

    - name: postgresql user
      postgresql_user: db=spinta name=atviriduomenys priv=ALL
      become_user: postgres

    - name: git clone manifest
      git: repo=https://gitlab.com/atviriduomenys/manifest.git dest={{ home }}/manifest force=yes
      notify: restart spinta
      become_user: atviriduomenys
      register: manifest

    - name: git clone spinta
      git: repo=https://gitlab.com/atviriduomenys/spinta.git dest={{ home }}/spinta force=yes
      notify: restart spinta
      become_user: atviriduomenys
      register: spinta

    - name: git clone pyenv
      git: repo=https://github.com/pyenv/pyenv.git dest={{ home }}/pyenv update=no
      become_user: atviriduomenys
      register: pyenv

    - name: install python 3.7.2
      command: "{{ home }} pyenv/bin/pyenv install 3.7.2 creates={{ home }}/pyenv/versions/3.7.2/bin/python"
      when: pyenv.changed

    - name: install requirements
      pip:
        chdir: "{{ home }}"
        virtualenv: env
        virtualenv_python: pyenv/versions/3.7.2/bin/python
        requirements: spinta/requirements.txt
        state: present
      become_user: atviriduomenys
      when: spinta.changed

    - name: install spinta
      pip:
        chdir: "{{ home }}"
        virtualenv: env
        virtualenv_python: pyenv/versions/3.7.2/bin/python
        name: "{{ home }}/spinta"
        editable: true
        state: present
      become_user: atviriduomenys
      when: spinta.changed

    - name: install manifest
      pip:
        chdir: "{{ home }}"
        virtualenv: env
        virtualenv_python: pyenv/versions/3.7.2/bin/python
        name: "{{ home }}/manifest"
        editable: true
        state: present
      become_user: atviriduomenys
      when: manifest.changed

    - name: spinta config file
      template: src=templates/env.j2 dest={{ home }}/.env
      notify: restart spinta

    - name: migrate database
      command: env/bin/spinta migrate chdir={{ home }}
      become_user: atviriduomenys
      when: manifest.changed

    - name: spinta systemd service
      template: src=templates/spinta.service.j2 dest=/etc/systemd/system/spinta.service
      notify:
        - reload systemd 
        - restart spinta

    - name: spinta systemd socket
      template: src=templates/spinta.socket.j2 dest=/etc/systemd/system/spinta.socket
      notify:
        - reload systemd 
        - restart spinta

    - name: spinta systemd tmpfile
      template: src=templates/spinta.tmpfile.j2 dest=/usr/lib/tmpfiles.d/spinta.conf
      notify:
        - reload systemd 
        - restart spinta

    - stat: path=/etc/letsencrypt/live/atviriduomenys.lt
      register: letsencryptcert
     
    - name: apache config file
      template: src=templates/apache.conf.j2 dest=/etc/apache2/sites-enabled/atviriduomenys.lt.conf
      notify: reload apache

    - name: create log dir
      file: path=/var/log/apache2/atviriduomenys.lt state=directory

    - name: create data dir
      file: path={{ home }}/www/data state=directory
      become_user: atviriduomenys

    - name: start spinta
      service: name=apache2 state=started

    - name: start apache
      service: name=apache2 state=started

    # Let's Encrypt

    - name: "let's encrypt: apt packages"
      apt:
        pkg:
          - libaugeas0
          - libssl-dev
          - libffi-dev
          - ca-certificates
        state: latest

    - name: "let's encrypt: pip packages"
      pip:
        name:
          - letsencrypt
          - letsencrypt-apache
        state: latest
        virtualenv: /opt/letsencrypt

    - name: "let's encrypt!"
      command: >
        /opt/letsencrypt/bin/letsencrypt certonly
          --text
          --agree-tos
          --non-interactive
          --expand
          --domain atviriduomenys.lt
          --domain www.atviriduomenys.lt
          --email sirexas@gmail.com
          --authenticator apache
        creates=/etc/letsencrypt/live/atviriduomenys.lt
      notify: reload apache
      register: letsencrypt

    - name: "let's encrypt: watch changes"
      stat: path=/etc/letsencrypt/live/atviriduomenys.lt
      register: letsencryptcert
      when: letsencrypt.changed

    - name: "let's encrypt: apache config after letsencrypt"
      template: src=templates/apache.conf.j2 dest=/etc/apache2/sites-enabled/atviriduomenys.lt.conf
      notify: reload apache
      when: letsencrypt.changed

  handlers:

    - name: reload systemd
      systemd: daemon_reload=yes

    - name: reload apache
      service: name=apache2 state=reloaded

    - name: restart spinta
      service: name=apache2 state=restarted
