---
- hosts: all
  sudo: yes
  gather_facts: yes


  vars:
    home: /opt/manopozicija.lt
    path: "{{ home }}/app"
    env: production

  vars_files:
    - vars/{{ env }}.yml


  tasks:

  - fail: msg="Ansible version 1.9 or greater required."
    when: ansible_version.full | version_compare('1.9', '<')

  - name: update locale
    locale_gen: name={{ item }} state=present
    with_items:
    - en_US.UTF-8
    - lt_LT.UTF-8

  - name: apt repositories
    apt_repository: repo='deb-src http://ubuntu-archive.mirror.serveriai.lt/ trusty main restricted universe' state=present

  - name: apt packages
    apt: pkg={{ item }} state=latest
    with_items:
    - build-essential
    - postgresql
    - python-psycopg2
    - python-dev
    - python-pip
    - python-virtualenv
    - apache2
    - libapache2-mod-wsgi-py3
    - git

    # Lets encrypt
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates

  - name: create user
    user: name=manopozicija system=yes group=www-data home={{ home }}

  - name: postgresql database
    postgresql_db: >
      name=manopozicija
      encoding='UTF-8'
      lc_collate='C.UTF-8'
      lc_ctype='C.UTF-8'
      template='template0'
    sudo_user: postgres

  - name: postgresql user
    postgresql_user: db=manopozicija name=manopozicija priv=ALL
    sudo_user: postgres

  - name: clone repository
    git: repo=https://github.com/sirex/manopozicija.lt.git dest={{ path }} force=yes
    notify: reload apache
    sudo_user: manopozicija
    tags: upload

  - name: install app dependencies
    command: make ubuntu chdir={{ path }}

  - name: init buildout
    command: python3 scripts/genconfig.py config/env/{{ env }}.cfg chdir={{ path }}
    sudo_user: manopozicija

  - name: build project
    command: make chdir={{ path }}
    sudo_user: manopozicija
    tags: upload

  - name: migrate database
    command: bin/django migrate --noinput chdir={{ path }}
    sudo_user: postgres
    tags: upload

  - name: collectstatic
    command: bin/django collectstatic --noinput chdir={{ path }}
    sudo_user: manopozicija
    tags: upload

  # Apache

  - name: enabled apache modules
    apache2_module: name={{ item }} state=present
    with_items:
    - rewrite
    - ssl
    notify: restart apache

  - stat: path=/etc/letsencrypt/live/{{ server_name }}
    register: letsencryptcert

  - name: set up apache virtual host
    template: src=templates/apache.conf dest=/etc/apache2/sites-enabled/manopozicija.lt.conf
    notify: reload apache

  - name: create log dir
    file: path=/var/log/apache2/manopozicija.lt state=directory

  - name: start apache
    service: name=apache2 state=started

  # Let's Encrypt

  - name: install letsencrypt
    pip: name={{ item }} virtualenv=/opt/letsencrypt state=latest
    with_items:
    - letsencrypt
    - letsencrypt-apache

  - name: let's encrypt!
    command: >
      /opt/letsencrypt/bin/letsencrypt certonly
        --text
        --agree-tos
        --non-interactive
        --expand
        --domain manopozicija.lt
        --domain www.manopozicija.lt
        --email sirexas@gmail.com
        --authenticator apache
      creates=/etc/letsencrypt/live/manopozicija.lt
    notify: reload apache
    register: letsencrypt

  - stat: path=/etc/letsencrypt/live/manopozicija.lt
    register: letsencryptcert
    when: letsencrypt.changed

  - name: apache config after letsencrypt
    template: src=templates/apache.conf dest=/etc/apache2/sites-enabled/manopozicija.lt.conf
    notify: reload apache
    when: letsencrypt.changed


  handlers:

  - name: reload source code
    command: touch --no-create {{ path }}/bin/django.wsgi

  - name: reload apache
    service: name=apache2 state=reloaded
