Vagrant.require_version ">= 1.6"

Vagrant.configure('2') do |config|
  config.vm.define 'box' do |box|
    box.vm.box = 'ubuntu/trusty64'
    box.vm.network :forwarded_port, guest: 80, host: 8080
    box.vm.network :private_network, ip: "10.0.0.4"
    box.vm.synced_folder '.', '/vagrant', disabled: true
    box.vm.synced_folder 'backups', '/tmp/backups'
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deploy.yml"
  end
end
