---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:

  - name: apt packages
    apt: pkg={{ item }} state=latest
    with_items:
    - apache2

    # Lets encrypt
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates

  # Apache

  - name: enabled apache modules
    apache2_module: name={{ item }} state=present
    with_items:
    - rewrite
    - ssl
    notify: restart apache

  - stat: path=/etc/letsencrypt/live/pycon.lt
    register: letsencryptcert

  - name: set up apache virtual host
    template: src=templates/apache.conf.j2 dest=/etc/apache2/sites-enabled/pycon.lt.conf
    notify: reload apache

  - name: create log dir
    file: path=/var/log/apache2/pycon.lt state=directory

  - name: start apache
    service: name=apache2 state=started

  # Let's Encrypt

  - name: install letsencrypt
    pip: name={{ item }} virtualenv=/opt/letsencrypt state=latest
    with_items:
    - letsencrypt
    - letsencrypt-apache

  - name: let's encrypt!
    command: >
      /opt/letsencrypt/bin/letsencrypt certonly
        --text
        --agree-tos
        --non-interactive
        --expand
        --domain pycon.lt
        --domain www.pycon.lt
        --email sirexas@gmail.com
        --authenticator apache
      creates=/etc/letsencrypt/live/pycon.lt
    notify: reload apache
    register: letsencrypt

  - stat: path=/etc/letsencrypt/live/pycon.lt
    register: letsencryptcert
    when: letsencrypt.changed

  - name: apache config after letsencrypt
    template: src=templates/apache.conf.j2 dest=/etc/apache2/sites-enabled/pycon.lt.conf
    notify: reload apache
    when: letsencrypt.changed


  handlers:

  - name: reload source code
    command: touch --no-create {{ path }}/bin/django.wsgi

  - name: reload apache
    service: name=apache2 state=reloaded

  - name: restart apache
    service: name=apache2 state=restarted
